### ISSUE TITLE
snapper fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by jlcenter** [openSUSE/snapper#133]
Hi,

I'm trying to build snapper on Ubuntu 14.04 x64 & I'm getting the following errors:

In file included from Btrfs.cc:34:0:
/usr/include/libmount/libmount.h:345:28: error: expected ',' or '...' before 'new'
       struct libmnt_table *new);
                            ^
Btrfs.cc: In constructor 'snapper::MntTable::MntTable()':
Btrfs.cc:1386:40: error: 'mnt_table_enable_comments' was not declared in this scope
      mnt_table_enable_comments(table, 1);
                                        ^
Btrfs.cc: In member function 'void snapper::MntTable::replace_file()':
Btrfs.cc:1402:52: error: 'mnt_table_replace_file' was not declared in this scope
      if (mnt_table_replace_file(table, "/etc/fstab") != 0)
                                                    ^
What am I missing?

Thanks.

    -John

**Comment by aschnell** [comment]
No response within four weeks. Assuming it works with newer libmount.

**Comment by udomsak** [comment]
@aschnell  it still error effect are Ubuntu 14.10 , 13.10  both use libmount same version -  libmount-dev                                                2.20.1-5.1ubuntu9   

```
In file included from Btrfs.cc:34:0:
/usr/include/libmount/libmount.h:345:28: error: expected ',' or '...' before 'new'
       struct libmnt_table *new);
                            ^
Btrfs.cc: In constructor 'snapper::MntTable::MntTable(const string&)':
Btrfs.cc:1403:40: error: 'mnt_table_enable_comments' was not declared in this scope
      mnt_table_enable_comments(table, 1);
                                        ^
Btrfs.cc: In member function 'void snapper::MntTable::replace_file()':
Btrfs.cc:1419:62: error: 'mnt_table_replace_file' was not declared in this scope
      if (mnt_table_replace_file(table, target_fstab().c_str()) != 0)
                                                              ^
make[2]: *** [Btrfs.lo] Error 1
make[2]: Leaving directory `/mnt/btrfs-mount/snapper-0.2.6/snapper'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/btrfs-mount/snapper-0.2.6'
make: *** [all] Error 2

```

**Comment by aschnell** [comment]
Well, you need a newer version of libmount. Or use the workaround I mentioned.
