### ISSUE TITLE
Building against btrfs-progs 4.20: BtrfsUtils.cc:145:24: error: ‘btrfs_qgroup_inherit’ was not declared in this scope

### ISSUE THREAD

**Issue by GreatEmerald** [openSUSE/snapper#473]
We have a bug report that snapper won't compile against btrfs-progs 4.20. See the full build log here: https://bugs.gentoo.org/attachment.cgi?id=562374

Downstream bug: https://bugs.gentoo.org/675974

**Comment by aschnell** [comment]
The build.log shows that libbtrfs cannot the found:

checking for btrfs_read_and_process_send_stream in -lbtrfs... no

Since the gentoo bug also notices that snapper stops working in the system I suspect that some linking error make the configure check for libbtrfs fail.

**Comment by aschnell** [comment]
The configure check fails indeed with:

configure:16619: gcc -o conftest -O2 -g -Wall -fmessage-length=0 -std=c99 -Wall -Wextra -Wformat -Wmissing-prototypes -Wno-unused-parameter  -DCONFDIR='"/etc/sysconfig"'  conftest.c -lbtrfs   >&5
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `btrfs_alloc_path'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `btrfs_extend_item'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `btrfs_insert_empty_items'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `btrfs_free_path'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `read_extent_buffer'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `btrfs_mark_buffer_dirty'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `write_extent_buffer'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/8/../../../../lib64/libbtrfs.so: undefined reference to `btrfs_search_slot'
collect2: error: ld returned 1 exit status

Looks like a problem of btrfs-progs to me.

**Comment by GreatEmerald** [comment]
Ah, nice catch, thanks!

**Comment by aschnell** [comment]
There were such problems before, e.g. https://github.com/openSUSE/snapper/issues/128.

**Comment by aschnell** [comment]
I informed David Sterba about the problem.

**Comment by kdave** [comment]
Bisected to commit 75b5eabb61def2319e

**Comment by kdave** [comment]
Fix released in version v4.20.1
